"use client";

import { useRive, type ViewModelInstance } from "@rive-app/react-canvas";
import { useCallback, useEffect, useRef, useState } from "react";
import {
  Bubble,
  bubbleWriter,
  LAYOUT,
  TYPE_MS,
  watchTheme,
} from "./rive-avatar";

/**
 * The avatar as a guide for one section (public/guide.riv, generated by
 * scripts/guide-rive.mjs). He stands behind the section's right border as if
 * at a door: when the section reaches the middle of the screen he leans out,
 * waves with his right hand and talks in a speech balloon; he comments on the
 * cards crossing the middle of the screen, and when the visitor leaves the
 * section he pleads, waves goodbye and leans back behind the border. Glued to
 * the border, he scrolls with the section and stays mid-screen while it is in
 * view. Between lines he lives a little (glances, leans in, thinks, smiles,
 * follows the cursor), and his hand varies: the wave is only for hello and,
 * sometimes, goodbye. Cards opt in with `data-guide="<key>"`, keyed like
 * `lines.hints`.
 */

export type GuideLines = {
  enter: string[];
  back: string[];
  leave: string[];
  fast: string[];
  hints: Record<string, string>;
};

const SRC = "/guide.riv";
const ART = { w: 84, h: 132 }; // the Guide artboard
const BUBBLE = { w: 210, h: 104, tip: [24, 98] }; // the Bubble artboard
const AIM = [40, 36]; // where the balloon's tail points, in Guide units
const MIN_MARGIN = 160; // px of page margin beside the border, for a legible balloon
const FAST_SCROLL = 2.2; // px/ms: "don't scroll so fast"
const HINT_GAP = 1600;
const pick = <T = string>(items: T[]) =>
  items[Math.floor(Math.random() * items.length)];

// Must match the order in scripts/guide-rive.mjs (GESTURES, MOODS).
const GESTURES = ["away", "wave", "explain", "point", "thumb"] as const;
const MOODS = [
  "neutral",
  "happy",
  "surprised",
  "thinking",
  "plead",
  "joy",
] as const;
type Gesture = (typeof GESTURES)[number];
type Mood = (typeof MOODS)[number];
const clamp = (v: number, min: number, max: number) =>
  Math.min(max, Math.max(min, v));

/** Sizes in px: the guide, the balloon, and how they stack. */
type Layout = {
  guide: { w: number; h: number; top: number };
  bubble: { w: number; h: number; left: number };
  height: number;
};

function layout(margin: number): Layout | null {
  if (margin < MIN_MARGIN) return null;
  const gw = clamp(margin - 12, 96, 190);
  const gh = (gw * ART.h) / ART.w;
  const bw = clamp(margin - 16, 150, 270);
  const bh = (bw * BUBBLE.h) / BUBBLE.w;
  const tip = [
    (BUBBLE.tip[0] / BUBBLE.w) * bw,
    (BUBBLE.tip[1] / BUBBLE.h) * bh,
  ];
  const aim = [(AIM[0] / ART.w) * gw, (AIM[1] / ART.h) * gh];
  const top = tip[1] - aim[1];
  // The tail aims at his head, as long as the balloon stays in the margin.
  const left = clamp(aim[0] - tip[0], 4, margin - 8 - bw);
  return {
    guide: { w: gw, h: gh, top },
    bubble: { w: bw, h: bh, left },
    height: Math.max(bh, top + gh),
  };
}

export default function Guide({
  sectionId,
  lines,
}: {
  sectionId: string;
  lines: GuideLines;
}) {
  const [box, setBox] = useState<Layout | null>(null);
  const bubble = useRef<ViewModelInstance | null>(null);
  const onBubble = useCallback((vmi: ViewModelInstance | null) => {
    bubble.current = vmi;
  }, []);
  const words = useRef(lines);
  words.current = lines;
  const stack = useRef(0);
  stack.current = box?.height ?? 0;

  const { rive, canvas, RiveComponent } = useRive({
    src: SRC,
    artboard: "Guide",
    stateMachine: "Guide",
    autoplay: true,
    autoBind: true,
    layout: LAYOUT,
  });

  // Room beside the border?
  useEffect(() => {
    const section = document.getElementById(sectionId);
    if (!section) return;
    const measure = () => {
      const right = section.getBoundingClientRect().right;
      setBox(layout(document.documentElement.clientWidth - right - 1));
    };
    measure();
    addEventListener("resize", measure);
    return () => removeEventListener("resize", measure);
  }, [sectionId]);

  const shown = box !== null;
  useEffect(() => {
    const vmi = rive?.viewModelInstance;
    const section = document.getElementById(sectionId);
    if (!vmi || !section || !shown) return;
    const cleanups: (() => void)[] = [watchTheme(vmi)];
    const bool = (name: string, value: boolean) => {
      const prop = vmi.boolean(name);
      if (prop) prop.value = value;
    };
    const num = (name: string, value: number) => {
      const prop = vmi.number(name);
      if (prop) prop.value = value;
    };
    const gesture = (g: Gesture) => num("gesture", GESTURES.indexOf(g));
    const mood = (m: Mood) => num("mood", MOODS.indexOf(m));

    // --- eased values: leaning in/out, where he looks ------------------------
    const eased = { reach: [0, 0], lookX: [0, 0], lookY: [0, 0] };
    type Eased = keyof typeof eased;
    let raf = 0;
    const step = () => {
      let moving = false;
      for (const [name, v] of Object.entries(eased)) {
        v[0] += (v[1] - v[0]) * 0.09;
        if (Math.abs(v[1] - v[0]) > 0.002) moving = true;
        else v[0] = v[1];
        num(name, v[0]);
      }
      raf = moving ? requestAnimationFrame(step) : 0;
    };
    const ease = (name: Eased, target: number) => {
      eased[name][1] = target;
      if (!raf) raf = requestAnimationFrame(step);
    };
    cleanups.push(() => cancelAnimationFrame(raf));
    // A scripted look holds for a while; otherwise his eyes follow the cursor.
    let lookUntil = 0;
    const look = (x: number, y: number, ms: number) => {
      lookUntil = Date.now() + ms;
      ease("lookX", x);
      ease("lookY", y);
    };
    const onPointer = (e: PointerEvent) => {
      if (Date.now() < lookUntil || !canvas) return;
      const r = canvas.getBoundingClientRect();
      ease("lookX", clamp((e.clientX - (r.left + r.width / 3)) / 400, -1, 1));
      ease("lookY", clamp((e.clientY - (r.top + r.height / 2)) / 400, -1, 1));
    };
    addEventListener("pointermove", onPointer, { passive: true });
    cleanups.push(() => removeEventListener("pointermove", onPointer));

    // --- scripts: little timed sequences, one at a time ---------------------
    let scriptTimer = 0;
    let scripted = false;
    let idling = false; // the running script is an idle beat, fine to cut
    const script = (steps: [number, () => void][], idle = false) => {
      clearTimeout(scriptTimer);
      idling = idle;
      let i = 0;
      const next = () => {
        scripted = i < steps.length;
        if (!scripted) {
          idling = false;
          return;
        }
        const [ms, fn] = steps[i++];
        scriptTimer = window.setTimeout(() => {
          fn();
          next();
        }, ms);
      };
      next();
    };

    // --- talking --------------------------------------------------------------
    const writer = bubbleWriter(bubble);
    let quietTimer = 0;
    let talking = false;
    let lastSaid = 0;
    cleanups.push(() => {
      writer.close();
      clearTimeout(scriptTimer);
      clearTimeout(quietTimer);
    });
    /** Back to rest: hand behind the frame, plain face, upright. */
    const settle = () => {
      gesture("away");
      mood("neutral");
      ease("reach", 0);
    };
    let hint = () => {}; // presents the card in the middle, defined below
    /** Says a line with a gesture and a face; the mouth moves while it is written. */
    const say = (
      text: string,
      {
        hand = "explain",
        face = "neutral",
        next = settle,
      }: { hand?: Gesture; face?: Mood; next?: () => void } = {},
    ) => {
      lastSaid = Date.now();
      talking = true;
      writer.cancel();
      clearTimeout(quietTimer);
      gesture(hand);
      mood(face);
      bool("isTalking", true);
      writer.pop(text, {
        typeMs: TYPE_MS.reply,
        linger: (t) => 1300 + t.length * 24,
        onTyped: () => {
          quietTimer = window.setTimeout(() => {
            bool("isTalking", false);
            // Beats stop with the words; held signs (point, thumb) stay.
            if (hand === "explain") gesture("away");
          }, 600);
        },
        after: () => {
          talking = false;
          lastSaid = Date.now();
          next();
        },
      });
    };

    // --- the visit --------------------------------------------------------------
    let inside = false;
    let present = false; // leaning out, or about to
    let visited = false;
    let hinted = new Set<string>();
    let current: string | null = null;
    // Scroll speed over the last 300 ms, sampled on every scroll event.
    const samples: [number, number][] = [];
    const speed = () => {
      const now = performance.now();
      while (samples.length && now - samples[0][0] > 300) samples.shift();
      if (samples.length < 2) return 0;
      const [t0, y0] = samples[0];
      const [t1, y1] = samples[samples.length - 1];
      return Math.abs(y1 - y0) / Math.max(16, t1 - t0);
    };
    let hintTimer = 0;
    let leaveTimer = 0;
    cleanups.push(() => {
      clearTimeout(hintTimer);
      clearTimeout(leaveTimer);
    });

    const goodbye = () => {
      if (inside) return settle();
      present = false;
      settle();
      bool("here", false);
    };
    const arrive = () => {
      hinted = new Set();
      ease("reach", 0);
      const back = words.current.back;
      // Caught before he was gone: a start, then glad.
      if (present)
        return script([
          [0, () => mood("surprised")],
          [420, () => say(pick(back), { hand: "thumb", face: "happy" })],
        ]);
      present = true;
      bool("here", true);
      if (!visited) {
        // The first time only: he waves hello.
        visited = true;
        return script([
          [
            700,
            () => {
              mood("joy");
              gesture("wave");
            },
          ],
          [
            1300,
            () =>
              say(pick(words.current.enter), {
                hand: pick<Gesture>(["explain", "point", "away"]),
                face: "happy",
              }),
          ],
        ]);
      }
      script(
        pick<[number, () => void][]>([
          [[750, () => say(pick(back), { hand: "explain", face: "happy" })]],
          [[750, () => say(pick(back), { hand: "thumb", face: "happy" })]],
          [
            [650, () => mood("surprised")],
            [380, () => say(pick(back), { hand: "point", face: "happy" })],
          ],
        ]),
      );
    };
    const leave = () => {
      clearTimeout(hintTimer);
      if (speed() > FAST_SCROLL) {
        // Startled: leans back, "wait!" with a raised finger.
        return script([
          [
            0,
            () => {
              mood("surprised");
              gesture("away");
              ease("reach", -0.45);
            },
          ],
          [
            320,
            () =>
              say(pick(words.current.fast), {
                hand: "point",
                face: "surprised",
                next: goodbye,
              }),
          ],
        ]);
      }
      // Pleads with an open hand, then sometimes waves goodbye.
      script([
        [
          0,
          () => {
            mood("plead");
            ease("reach", 0.4);
          },
        ],
        [
          200,
          () =>
            say(pick(words.current.leave), {
              hand: "explain",
              face: "plead",
              next: () => {
                if (inside || Math.random() < 0.6) return goodbye();
                script([
                  [
                    0,
                    () => {
                      mood("joy");
                      gesture("wave");
                    },
                  ],
                  [1100, goodbye],
                ]);
              },
            }),
        ],
      ]);
    };
    hint = () => {
      if (!inside) return;
      // Cards crossing the middle of the screen (a row, on two columns): the
      // first one not presented yet.
      const middle = innerHeight / 2;
      const key =
        [...section.querySelectorAll<HTMLElement>("[data-guide]")]
          .filter((el) => {
            const r = el.getBoundingClientRect();
            return r.top < middle && r.bottom > middle;
          })
          .map((el) => el.dataset.guide ?? "")
          .find((k) => words.current.hints[k] && !hinted.has(k)) ?? null;
      current = key;
      if (!key) return;
      // Let the previous line be read first; try again if the card is still there.
      const busy = talking || (scripted && !idling);
      const wait = busy ? 1000 : lastSaid + HINT_GAP - Date.now();
      clearTimeout(hintTimer);
      if (wait > 0) {
        hintTimer = window.setTimeout(() => current === key && hint(), wait);
        return;
      }
      hinted.add(key);
      // A glance at the card, leaning in, then the comment.
      script([
        [
          0,
          () => {
            look(-0.85, 0.6, 900);
            ease("reach", 0.5);
          },
        ],
        [
          700,
          () =>
            say(words.current.hints[key], {
              hand: pick<Gesture>(["point", "thumb", "explain", "away"]),
              face: pick<Mood>(["happy", "neutral"]),
              // The other card of the row, if the visitor stays on it.
              next: () => {
                settle();
                hintTimer = window.setTimeout(hint, HINT_GAP);
              },
            }),
        ],
      ]);
    };

    // --- idle: small things while he waits, never a wave ---------------------
    const IDLE: [number, [number, () => void][]][] = [
      [3, [[0, () => look(-0.85, 0.55, 1700)]]], // glances at the cards
      [
        2,
        [
          [
            0,
            () => {
              ease("reach", 0.7);
              mood("happy");
            },
          ],
          [1500, settle],
        ],
      ], // leans in, curious
      [
        2,
        [
          [
            0,
            () => {
              mood("thinking");
              look(0.3, -0.9, 2200);
            },
          ],
          [2200, () => mood("neutral")],
        ],
      ], // thinks it over
      [
        2,
        [
          [0, () => mood("happy")],
          [1500, () => mood("neutral")],
        ],
      ], // smiles
      [
        1,
        [
          [
            0,
            () => {
              gesture("thumb");
              mood("happy");
            },
          ],
          [1300, settle],
        ],
      ], // thumbs up
      [
        1,
        [
          [0, () => ease("reach", -0.6)],
          [1300, () => ease("reach", 0)],
        ],
      ], // shy, leans back
      [2, []], // nothing
    ];
    let idleTimer = 0;
    const idle = () => {
      idleTimer = window.setTimeout(idle, 3500 + Math.random() * 3500);
      if (!present || !inside || talking || scripted) return;
      hint(); // a card waiting comes first
      if (talking || scripted || Date.now() - lastSaid < 3000) return;
      const total = IDLE.reduce((sum, [w]) => sum + w, 0);
      let r = Math.random() * total;
      for (const [weight, steps] of IDLE) {
        r -= weight;
        if (r < 0) return script(steps, true);
      }
    };
    idle();
    cleanups.push(() => clearTimeout(idleTimer));

    let frame = 0;
    const check = () => {
      frame = 0;
      // In while the section covers the middle of the screen; out as soon as
      // its end starts pushing him up (so his goodbye is still on screen).
      const r = section.getBoundingClientRect();
      const isInside =
        r.top < innerHeight * 0.55 &&
        r.bottom > innerHeight / 2 + stack.current / 2;
      if (isInside !== inside) {
        inside = isInside;
        clearTimeout(leaveTimer);
        if (inside) arrive();
        // A moment to measure how fast the visitor is going.
        else leaveTimer = window.setTimeout(() => !inside && leave(), 150);
      } else if (inside) hint();
    };
    const onScroll = () => {
      samples.push([performance.now(), scrollY]);
      if (!frame) frame = requestAnimationFrame(check);
    };
    addEventListener("scroll", onScroll, { passive: true });
    cleanups.push(() => {
      removeEventListener("scroll", onScroll);
      cancelAnimationFrame(frame);
    });
    check();
    return () => {
      for (const fn of cleanups) fn();
    };
  }, [rive, canvas, sectionId, shown]);

  if (!box) return null;
  return (
    <div
      aria-hidden
      className="pointer-events-none absolute inset-y-0 left-full ml-px"
      style={{ width: Math.max(box.guide.w, box.bubble.left + box.bubble.w) }}
    >
      <div
        className="sticky"
        style={{ top: `calc(50vh - ${box.height / 2}px)`, height: box.height }}
      >
        <div
          className="absolute z-10"
          style={{
            left: box.bubble.left,
            top: 0,
            width: box.bubble.w,
            height: box.bubble.h,
          }}
        >
          <Bubble src={SRC} artboard="Bubble" onBind={onBubble} />
        </div>
        <div
          className="absolute left-0"
          style={{
            top: box.guide.top,
            width: box.guide.w,
            height: box.guide.h,
          }}
        >
          <RiveComponent className="size-full" />
        </div>
      </div>
    </div>
  );
}
