/**
 * Remote control for the hero's Rive avatar (public/avatar.riv, generated by
 * scripts/avatar-rive.mjs). Anything on the page, like a future chat, drives
 * it through `avatar` without holding a reference to the Rive instance; calls
 * made before the avatar has loaded (or when it is not mounted) are no-ops.
 */

export const MOODS = [
  "neutral",
  "happy",
  "laughing",
  "thinking",
  "surprised",
  "confused",
  "sleepy",
  "focused",
] as const;
export type Mood = (typeof MOODS)[number];

/** One-shot reactions; `poke` branches on humor (>= 50 laughs, else "meh"). */
export type AvatarTrigger = "wave" | "poke" | "solve" | "celebrate";

export type AvatarDriver = {
  setMood: (mood: Mood) => void;
  getMood: () => Mood;
  /** 0-100: how the avatar takes a poke. */
  setHumor: (humor: number) => void;
  getHumor: () => number;
  fire: (trigger: AvatarTrigger) => void;
  setTalking: (talking: boolean) => void;
  setTyping: (typing: boolean) => void;
};

/** Emitted from the Rive file (e.g. the visitor clicked the avatar's head). */
export type AvatarEvent = { type: "poke" };

let driver: AvatarDriver | null = null;
const subscribers = new Set<(event: AvatarEvent) => void>();

export const avatar = {
  setMood: (mood: Mood) => driver?.setMood(mood),
  getMood: (): Mood => driver?.getMood() ?? "neutral",
  setHumor: (humor: number) => driver?.setHumor(humor),
  getHumor: () => driver?.getHumor() ?? 60,
  fire: (trigger: AvatarTrigger) => driver?.fire(trigger),
  setTalking: (talking: boolean) => driver?.setTalking(talking),
  setTyping: (typing: boolean) => driver?.setTyping(typing),
  get ready() {
    return driver !== null;
  },
  on(listener: (event: AvatarEvent) => void) {
    subscribers.add(listener);
    return () => {
      subscribers.delete(listener);
    };
  },
};

export function connectAvatar(next: AvatarDriver) {
  driver = next;
  return () => {
    if (driver === next) driver = null;
  };
}

export function emitAvatarEvent(event: AvatarEvent) {
  for (const listener of subscribers) listener(event);
}
