// ---------------------------------------------------------------------------
// Portfolio data: single source of truth for every page of the site.
// ---------------------------------------------------------------------------

export type Career = {
  company: string;
  role: string;
  initial: string;
  period: string;
  type: string;
  location: string;
  current: boolean;
  isEdu?: boolean;
  summary: string;
  responsibilities: string[];
  achievements: string[];
  skills: string[];
};

export type Project = {
  slug: string;
  name: string;
  tag: string;
  img: string;
  thumb: string;
  url: string | null;
  github: string | null;
  year: string;
  type: string;
  desc: string;
  overview: string;
  gallery: string[];
  tech: string[];
  highlights: string[];
  stats: { k: string; v: string }[];
};

export type Service = {
  label: string;
  title: string;
  body: string;
  features: string[];
};

export type StackGroup = { label: string; items: string[] };

export const PROFILE = {
  name: "Titosy Manankasina",
  headline: "Développeur Fullstack JavaScript / Flutter",
  email: "dev.titosy@gmail.com",
  photo: "/photo.jpg",
  github: "https://github.com/titoo-dev",
  linkedin: "https://www.linkedin.com/in/titosy-manankasina",
  // Generated by `pnpm cv` (scripts/generate-cv.mjs).
  cv: "/cv-titosy-manankasina.pdf",
  summary:
    "Spécialisé dans le développement logiciel, j'interviens à toutes les étapes d'un projet, de l'analyse des besoins à la réalisation des solutions. J'accompagne les clients dans le cadrage de leurs projets afin de bien comprendre leurs attentes et de proposer des solutions adaptées, simples et efficaces.",
  languages: [
    { name: "Français", level: "Professionnel complet" },
    { name: "Anglais", level: "Professionnel limité" },
  ],
} as const;

export const careers: Career[] = [
  {
    company: "Fluentech",
    role: "Développeur confirmé JavaScript / Flutter / Kotlin",
    initial: "F",
    period: "Depuis oct. 2025",
    type: "Hybride",
    location: "Antananarivo, Madagascar",
    current: true,
    summary:
      "Mise en place d'une solution SaaS tout-en-un pour l'accompagnement des professionnels, incluant plusieurs fonctionnalités métier : gestion de projet, automatisation de la création de business plans, analyse prévisionnelle et bilan, gestion de la facturation, etc.",
    responsibilities: [
      "Mise en place d'une architecture micro-frontend avec Next.js Multi-Zones pour accélérer la livraison et améliorer l'expérience de développement.",
      "Pilotage du workflow complet, du développement à la livraison, avec des méthodes déclaratives (Terraform, Kubernetes, ArgoCD, Prometheus, Grafana).",
      "Mise en place de solutions agentic avec Convex AI et Mastra AI.",
      "Mise en place des workflows avec Inngest.",
    ],
    achievements: [],
    skills: [
      "Next.js Multi-Zones",
      "Flutter",
      "Kotlin",
      "Terraform",
      "Kubernetes",
      "ArgoCD",
      "Prometheus",
      "Grafana",
      "Convex AI",
      "Mastra AI",
      "Inngest",
    ],
  },
  {
    company: "PUSH-IT",
    role: "Développeur Fullstack JavaScript",
    initial: "P",
    period: "Juil. 2025 à oct. 2025",
    type: "Hybride",
    location: "Antananarivo, Madagascar",
    current: false,
    summary:
      "Développement d'une application de gestion de licences logicielles.",
    responsibilities: [
      "Intégration de Cryptolens pour la gestion et la sécurisation des licences.",
      "Mise en place de la gestion des mises à jour logicielles avec Mender.io.",
      "Intégration de la facturation et des paiements via Zoho Book.",
      "Développement du frontend avec Next.js.",
      "Conception du backend avec Express, PostgreSQL, TypeORM et GraphQL.",
      "Organisation du projet en monorepo pour faciliter la maintenance et la collaboration.",
    ],
    achievements: [],
    skills: [
      "Next.js",
      "Express",
      "PostgreSQL",
      "TypeORM",
      "GraphQL",
      "Mender.io",
      "Zoho Book",
      "Cryptolens",
      "Monorepo",
    ],
  },
  {
    company: "Bocasay",
    role: "Développeur JavaScript",
    initial: "B",
    period: "Juil. 2022 à juil. 2025",
    type: "Hybride",
    location: "Antananarivo, Madagascar",
    current: false,
    summary:
      "Participation au développement et à la maintenance d'une application de gestion de la conformité réglementaire des produits chimiques, cosmétiques, biocides et dispositifs médicaux. Collaboration avec des équipes interfonctionnelles pour assurer la qualité, la performance et la livraison rapide des solutions.",
    responsibilities: [
      "Développement et maintenance des interfaces utilisateurs avec React et ExtJS.",
      "Intégration des fonctionnalités front-end avec les données du serveur via GraphQL.",
      "Participation aux daily meetings et aux plannings de sprint pour assurer l'alignement avec les objectifs du projet.",
    ],
    achievements: [],
    skills: ["React", "ExtJS", "GraphQL", "Scrum"],
  },
  {
    company: "Flit Soft",
    role: "Stagiaire développeur JavaScript & Flutter",
    initial: "FS",
    period: "Mars 2022 à juil. 2022",
    type: "À distance",
    location: "Antananarivo, Madagascar",
    current: false,
    summary:
      "Membre d'une équipe chargée des intégrations et des outils pour développeurs. Mission principale : améliorer et simplifier l'expérience des développeurs en optimisant les outils et les processus, en assurant leur accessibilité et en répondant aux besoins spécifiques des équipes techniques.",
    responsibilities: [
      "Intégration d'un paiement Mvola dans une application de partage de voiture et de chauffeurs de taxi.",
      "Création d'un générateur de code en Dart pour faciliter le développement.",
      "Participation active aux réunions régulières et présentation de propositions à travers l'entreprise.",
    ],
    achievements: [],
    skills: ["JavaScript", "Flutter", "Dart", "Mvola"],
  },
  {
    company: "ISPM",
    role: "Licence en ingénierie logicielle",
    initial: "🎓",
    period: "Oct. 2018 à oct. 2022",
    type: "Formation",
    location: "Antananarivo, Madagascar",
    current: false,
    isEdu: true,
    summary: "Institut Supérieur Polytechnique de Madagascar.",
    responsibilities: [],
    achievements: [],
    skills: [],
  },
];

export const projects: Project[] = [
  {
    slug: "tononkira",
    name: "Tononkira",
    tag: "Flutter · Web · Search",
    img: "/images/tononkira/tononkira_1.webp",
    thumb: "/images/tononkira/tononkira_2.webp",
    url: "https://tononkira.titosy.dev/",
    github: null,
    year: "2024",
    type: "Application Web & Mobile",
    desc: "Découverte des paroles de chansons malgaches : 15 000+ titres, 2 300 artistes, recherche intelligente & accès hors-ligne.",
    overview:
      "Plateforme complète dédiée à la découverte et l'exploration des paroles de chansons malgaches, offrant un accès à plus de 15 000 chansons de 2 300 artistes avec recherche intelligente, personnalisation et accès hors ligne.",
    gallery: [
      "/images/tononkira/tononkira_1.webp",
      "/images/tononkira/tononkira_2.webp",
      "/images/tononkira/tononkira_3.webp",
      "/images/tononkira/tononkira_4.webp",
    ],
    tech: ["Flutter", "Dart", "Next.js", "Search Engine", "Offline-first"],
    highlights: [
      "Application mobile Android avec Flutter offrant un accès hors ligne complet aux paroles.",
      "Moteur de recherche performant permettant de trouver des chansons par paroles, artiste ou titre.",
      "Système de favoris et de playlists personnalisées pour une expérience optimale.",
      "Optimisation des performances pour une application légère et rapide sur tous les appareils.",
      "Base de données de plus de 15 000 chansons et 2 300 artistes malgaches.",
    ],
    stats: [
      { k: "15 000+", v: "Chansons" },
      { k: "2 300", v: "Artistes" },
      { k: "100%", v: "Hors-ligne" },
    ],
  },
  {
    slug: "chantastik",
    name: "Chantastik",
    tag: "Remotion · Web Audio API",
    img: "/images/chantastik/chantastik_1.webp",
    thumb: "/images/chantastik/chantastik_2.webp",
    url: "https://chantastik.titosy.dev/",
    github: "https://github.com/titoo-dev/chantastik",
    year: "2024",
    type: "Application Web",
    desc: "Crée des vidéos lyriques animées depuis un fichier audio, avec synchronisation précise et export de fichiers LRC.",
    overview:
      "Une application qui permet de créer de superbes vidéos de paroles à partir de fichiers audio, avec de magnifiques animations et des effets visuels personnalisables.",
    gallery: [
      "/images/chantastik/chantastik_1.webp",
      "/images/chantastik/chantastik_2.webp",
      "/images/chantastik/chantastik_3.webp",
      "/images/chantastik/chantastik_4.webp",
    ],
    tech: ["Remotion", "Web Audio API", "React", "TypeScript", "LRC"],
    highlights: [
      "Rendu vidéo des paroles animées propulsé par Remotion.",
      "Web Audio API pour synchroniser précisément l'audio avec les animations.",
      "Système d'annotation des lyrics avec interface intuitive pour le timing.",
      "Génération automatique de fichiers LRC pour la compatibilité avec d'autres lecteurs.",
    ],
    stats: [
      { k: "Frame", v: "Sync parfaite" },
      { k: "LRC", v: "Export" },
      { k: "OSS", v: "Open source" },
    ],
  },
  {
    slug: "magape",
    name: "MAGAPE",
    tag: "Next.js · TypeScript · Tailwind",
    img: "/images/magape/magape_1.webp",
    thumb: "/images/magape/magape_2.webp",
    url: "https://megape.vercel.app/",
    github: null,
    year: "2024",
    type: "Plateforme communautaire",
    desc: "Plateforme communautaire chrétienne francophone avec podcasts, enseignements bibliques & boutique en ligne.",
    overview:
      "Plateforme dédiée à rassembler la communauté chrétienne francophone à travers des ressources enrichissantes, des contenus audiovisuels et des produits inspirants, créant des ponts d'unité entre les chrétiens.",
    gallery: [
      "/images/magape/magape_1.webp",
      "/images/magape/magape_2.webp",
      "/images/magape/magape_3.webp",
      "/images/magape/magape_4.webp",
    ],
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "CMS", "E-commerce"],
    highlights: [
      "Plateforme complète avec Next.js et TypeScript pour la francophonie chrétienne.",
      "Système de gestion de contenu pour podcasts, émissions et enseignements bibliques.",
      "Boutique en ligne intégrée pour les produits MAGAPE (maillots, ebooks, cahiers).",
      "Interface moderne et responsive avec Tailwind CSS.",
      "Cahier Magape Kids, un outil éducatif centré sur la Bible pour les enfants.",
    ],
    stats: [
      { k: "CMS", v: "Contenus" },
      { k: "Shop", v: "Boutique" },
      { k: "FR", v: "Francophone" },
    ],
  },
  {
    slug: "okani-survey",
    name: "Okani Survey",
    tag: "Next.js · Mobile · Gov",
    img: "/images/okani-survey/okani_1.webp",
    thumb: "/images/okani-survey/okani_2.webp",
    url: "https://okani-survey.vercel.app/",
    github: null,
    year: "2025",
    type: "Plateforme gouvernementale",
    desc: "Plateforme de sondage gouvernementale (Gabon) évaluant le service public foncier. Web + app cross-platform.",
    overview:
      "Plateforme de sondage gouvernementale officielle évaluant la satisfaction des usagers du service public foncier au Gabon, mandatée par la DGCBF dans le cadre de la modernisation de l'administration publique.",
    gallery: [
      "/images/okani-survey/okani_1.webp",
      "/images/okani-survey/okani_2.webp",
      "/images/okani-survey/okani_3.webp",
    ],
    tech: ["Next.js", "TypeScript", "Cross-platform", "Tailwind CSS", "Mobile"],
    highlights: [
      "Plateforme web interactive avec Next.js pour recueillir les retours des usagers.",
      "Application mobile cross-platform disponible sur App Store et Google Play.",
      "Processus de sondage simplifié en 6 étapes couvrant le parcours foncier (ANUTTC).",
      "Système de collecte de données anonyme et sécurisé garantissant la confidentialité.",
      "Déploiement ciblé : Libreville, Lambaréné et Mouila.",
    ],
    stats: [
      { k: "6", v: "Étapes" },
      { k: "5-10 min", v: "Durée" },
      { k: "3", v: "Villes" },
    ],
  },
];

export const services: Service[] = [
  {
    label: "Web",
    title: "Développement Web",
    body: "Applications web modernes et performantes avec React, Next.js et TypeScript.",
    features: [
      "React / Next.js",
      "Sites responsives",
      "Progressive Web Apps",
      "Intégration API",
    ],
  },
  {
    label: "Mobile",
    title: "Applications Mobile",
    body: "Applications cross-platform avec Flutter. Une expérience fluide sur iOS et Android.",
    features: [
      "Apps Flutter",
      "UI/UX mobile",
      "Intégration Firebase",
      "App Store & Play Store",
    ],
  },
  {
    label: "Design",
    title: "Design UI/UX",
    body: "Interfaces élégantes et accessibles avec Figma. Des designs modernes qui captivent.",
    features: [
      "Prototypage Figma",
      "Design System",
      "Interface responsive",
      "Accessibilité",
    ],
  },
  {
    label: "Conseil",
    title: "Consulting & Formation",
    body: "Accompagnement technique et formation de vos équipes sur les technologies modernes.",
    features: [
      "Audit technique",
      "Formation React/Flutter",
      "Code review",
      "Best practices",
    ],
  },
];

export const stack: StackGroup[] = [
  {
    label: "Frontend",
    items: ["Next.js", "React", "TypeScript", "Tailwind CSS", "ExtJS"],
  },
  {
    label: "Backend",
    items: [
      "Node.js",
      "Nest.js",
      "Express",
      "GraphQL",
      "PostgreSQL",
      "TypeORM",
    ],
  },
  {
    label: "Mobile",
    items: ["Flutter", "Dart", "Kotlin", "Firebase"],
  },
  {
    label: "DevOps",
    items: [
      "Terraform",
      "Kubernetes",
      "ArgoCD",
      "Prometheus",
      "Grafana",
      "Docker",
    ],
  },
  {
    label: "IA & Outils",
    items: [
      "Convex AI",
      "Mastra AI",
      "Inngest",
      "Claude Code",
      "LangGraph",
      "Langchain",
      "Figma",
    ],
  },
];

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
