// ---------------------------------------------------------------------------
// Portfolio data: single source of truth for every page of the site and the
// CV. Translatable fields are `{ fr, en }` pairs; `getContent(locale)` picks
// one language. Keep this file free of runtime imports: `pnpm cv` loads it
// directly with Node.
// ---------------------------------------------------------------------------

import type { Locale } from "./i18n";

type T<V = string> = { fr: V; en: V };

/** `V` where any string may instead be a `{ fr, en }` pair. */
type Localizable<V> = V extends string
  ? V | T<V>
  : V extends (infer E)[]
    ? Localizable<E>[]
    : V extends object
      ? { [K in keyof V]: Localizable<V[K]> }
      : V;

/** Swaps every `{ fr, en }` pair in `V` for its value. */
type Resolved<V> = V extends T<infer U>
  ? U
  : V extends readonly (infer E)[]
    ? Resolved<E>[]
    : V extends object
      ? { [K in keyof V]: Resolved<V[K]> }
      : V;

export type Career = {
  company: string;
  role: string;
  initial: string;
  period: string;
  type: string;
  location: string;
  current: boolean;
  isEdu?: boolean;
  summary: string;
  responsibilities: string[];
  achievements: string[];
  skills: string[];
};

export type Project = {
  slug: string;
  name: string;
  tag: string;
  img: string;
  thumb: string;
  url: string | null;
  github: string | null;
  year: string;
  type: string;
  desc: string;
  overview: string;
  gallery: string[];
  tech: string[];
  highlights: string[];
  stats: { k: string; v: string }[];
};

export type Service = {
  label: string;
  title: string;
  body: string;
  features: string[];
};

export type StackGroup = { label: string; items: string[] };

const PROFILE = {
  name: "Titosy Manankasina",
  headline: {
    fr: "Développeur Fullstack JavaScript / Flutter",
    en: "Fullstack JavaScript / Flutter Developer",
  },
  email: "dev.titosy@gmail.com",
  photo: "/photo.jpg",
  github: "https://github.com/titoo-dev",
  linkedin: "https://www.linkedin.com/in/titosy-manankasina",
  // Generated by `pnpm cv` (scripts/generate-cv.mjs).
  cv: {
    fr: "/cv-titosy-manankasina.pdf",
    en: "/cv-titosy-manankasina-en.pdf",
  },
  summary: {
    fr: "Spécialisé dans le développement logiciel, j'interviens à toutes les étapes d'un projet, de l'analyse des besoins à la réalisation des solutions. J'accompagne les clients dans le cadrage de leurs projets afin de bien comprendre leurs attentes et de proposer des solutions adaptées, simples et efficaces.",
    en: "Specialized in software development, I work at every stage of a project, from requirements analysis to delivering the solution. I help clients scope their projects so I fully understand their expectations and can offer tailored, simple and effective solutions.",
  },
  languages: [
    {
      name: { fr: "Français", en: "French" },
      level: {
        fr: "Professionnel complet",
        en: "Full professional proficiency",
      },
    },
    {
      name: { fr: "Anglais", en: "English" },
      level: {
        fr: "Professionnel limité",
        en: "Limited working proficiency",
      },
    },
  ],
};

const HYBRID = { fr: "Hybride", en: "Hybrid" };
const TANA = "Antananarivo, Madagascar";

const careers: Localizable<Career>[] = [
  {
    company: "Fluentech",
    role: {
      fr: "Développeur confirmé JavaScript / Flutter / Kotlin",
      en: "Experienced JavaScript / Flutter / Kotlin Developer",
    },
    initial: "F",
    period: { fr: "Depuis oct. 2025", en: "Since Oct. 2025" },
    type: HYBRID,
    location: TANA,
    current: true,
    summary: {
      fr: "Mise en place d'une solution SaaS tout-en-un pour l'accompagnement des professionnels, incluant plusieurs fonctionnalités métier : gestion de projet, automatisation de la création de business plans, analyse prévisionnelle et bilan, gestion de la facturation, etc.",
      en: "Building an all-in-one SaaS solution that supports professionals, with several business features: project management, automated business plan creation, financial forecasting and statements, invoicing, and more.",
    },
    responsibilities: [
      {
        fr: "Mise en place d'une architecture micro-frontend avec Next.js Multi-Zones pour accélérer la livraison et améliorer l'expérience de développement.",
        en: "Set up a micro-frontend architecture with Next.js Multi-Zones to speed up delivery and improve the developer experience.",
      },
      {
        fr: "Pilotage du workflow complet, du développement à la livraison, avec des méthodes déclaratives (Terraform, Kubernetes, ArgoCD, Prometheus, Grafana).",
        en: "Run the full workflow, from development to delivery, with declarative tooling (Terraform, Kubernetes, ArgoCD, Prometheus, Grafana).",
      },
      {
        fr: "Mise en place de solutions agentic avec Convex AI et Mastra AI.",
        en: "Build agentic AI solutions with Convex AI and Mastra AI.",
      },
      {
        fr: "Mise en place des workflows avec Inngest.",
        en: "Set up workflows with Inngest.",
      },
    ],
    achievements: [],
    skills: [
      "Next.js Multi-Zones",
      "Flutter",
      "Kotlin",
      "Terraform",
      "Kubernetes",
      "ArgoCD",
      "Prometheus",
      "Grafana",
      "Convex AI",
      "Mastra AI",
      "Inngest",
    ],
  },
  {
    company: "PUSH-IT",
    role: {
      fr: "Développeur Fullstack JavaScript",
      en: "Fullstack JavaScript Developer",
    },
    initial: "P",
    period: { fr: "Juil. 2025 à oct. 2025", en: "Jul. 2025 to Oct. 2025" },
    type: HYBRID,
    location: TANA,
    current: false,
    summary: {
      fr: "Développement d'une application de gestion de licences logicielles.",
      en: "Development of a software license management application.",
    },
    responsibilities: [
      {
        fr: "Intégration de Cryptolens pour la gestion et la sécurisation des licences.",
        en: "Integrated Cryptolens to manage and secure licenses.",
      },
      {
        fr: "Mise en place de la gestion des mises à jour logicielles avec Mender.io.",
        en: "Set up software update management with Mender.io.",
      },
      {
        fr: "Intégration de la facturation et des paiements via Zoho Book.",
        en: "Integrated billing and payments through Zoho Book.",
      },
      {
        fr: "Développement du frontend avec Next.js.",
        en: "Developed the frontend with Next.js.",
      },
      {
        fr: "Conception du backend avec Express, PostgreSQL, TypeORM et GraphQL.",
        en: "Designed the backend with Express, PostgreSQL, TypeORM and GraphQL.",
      },
      {
        fr: "Organisation du projet en monorepo pour faciliter la maintenance et la collaboration.",
        en: "Organized the project as a monorepo to ease maintenance and collaboration.",
      },
    ],
    achievements: [],
    skills: [
      "Next.js",
      "Express",
      "PostgreSQL",
      "TypeORM",
      "GraphQL",
      "Mender.io",
      "Zoho Book",
      "Cryptolens",
      "Monorepo",
    ],
  },
  {
    company: "Bocasay",
    role: { fr: "Développeur JavaScript", en: "JavaScript Developer" },
    initial: "B",
    period: { fr: "Juil. 2022 à juil. 2025", en: "Jul. 2022 to Jul. 2025" },
    type: HYBRID,
    location: TANA,
    current: false,
    summary: {
      fr: "Participation au développement et à la maintenance d'une application de gestion de la conformité réglementaire des produits chimiques, cosmétiques, biocides et dispositifs médicaux. Collaboration avec des équipes interfonctionnelles pour assurer la qualité, la performance et la livraison rapide des solutions.",
      en: "Contributed to the development and maintenance of a regulatory compliance application for chemicals, cosmetics, biocides and medical devices. Worked with cross-functional teams to ensure quality, performance and fast delivery.",
    },
    responsibilities: [
      {
        fr: "Développement et maintenance des interfaces utilisateurs avec React et ExtJS.",
        en: "Developed and maintained user interfaces with React and ExtJS.",
      },
      {
        fr: "Intégration des fonctionnalités front-end avec les données du serveur via GraphQL.",
        en: "Connected front-end features to server data through GraphQL.",
      },
      {
        fr: "Participation aux daily meetings et aux plannings de sprint pour assurer l'alignement avec les objectifs du projet.",
        en: "Took part in daily meetings and sprint planning to stay aligned with the project goals.",
      },
    ],
    achievements: [],
    skills: ["React", "ExtJS", "GraphQL", "Scrum"],
  },
  {
    company: "Flit Soft",
    role: {
      fr: "Stagiaire développeur JavaScript & Flutter",
      en: "JavaScript & Flutter Developer Intern",
    },
    initial: "FS",
    period: { fr: "Mars 2022 à juil. 2022", en: "Mar. 2022 to Jul. 2022" },
    type: { fr: "À distance", en: "Remote" },
    location: TANA,
    current: false,
    summary: {
      fr: "Membre d'une équipe chargée des intégrations et des outils pour développeurs. Mission principale : améliorer et simplifier l'expérience des développeurs en optimisant les outils et les processus, en assurant leur accessibilité et en répondant aux besoins spécifiques des équipes techniques.",
      en: "Member of a team in charge of integrations and developer tooling. Main mission: improve and simplify the developer experience by optimizing tools and processes, keeping them accessible and meeting the specific needs of technical teams.",
    },
    responsibilities: [
      {
        fr: "Intégration d'un paiement Mvola dans une application de partage de voiture et de chauffeurs de taxi.",
        en: "Integrated Mvola payments into a car-sharing and taxi-driver app.",
      },
      {
        fr: "Création d'un générateur de code en Dart pour faciliter le développement.",
        en: "Built a code generator in Dart to speed up development.",
      },
      {
        fr: "Participation active aux réunions régulières et présentation de propositions à travers l'entreprise.",
        en: "Took an active part in regular meetings and presented proposals across the company.",
      },
    ],
    achievements: [],
    skills: ["JavaScript", "Flutter", "Dart", "Mvola"],
  },
  {
    company: "ISPM",
    role: {
      fr: "Licence en ingénierie logicielle",
      en: "Bachelor's degree in Software Engineering",
    },
    initial: "🎓",
    period: { fr: "Oct. 2018 à oct. 2022", en: "Oct. 2018 to Oct. 2022" },
    type: { fr: "Formation", en: "Education" },
    location: TANA,
    current: false,
    isEdu: true,
    summary: "Institut Supérieur Polytechnique de Madagascar.",
    responsibilities: [],
    achievements: [],
    skills: [],
  },
];

const projects: Localizable<Project>[] = [
  {
    slug: "tononkira",
    name: "Tononkira",
    tag: "Flutter · Web · Search",
    img: "/images/tononkira/tononkira_1.webp",
    thumb: "/images/tononkira/tononkira_2.webp",
    url: "https://tononkira.titosy.dev/",
    github: null,
    year: "2024",
    type: { fr: "Application Web & Mobile", en: "Web & Mobile App" },
    desc: {
      fr: "Découverte des paroles de chansons malgaches : 15 000+ titres, 2 300 artistes, recherche intelligente & accès hors-ligne.",
      en: "Discover Malagasy song lyrics: 15,000+ songs, 2,300 artists, smart search & offline access.",
    },
    overview: {
      fr: "Plateforme complète dédiée à la découverte et l'exploration des paroles de chansons malgaches, offrant un accès à plus de 15 000 chansons de 2 300 artistes avec recherche intelligente, personnalisation et accès hors ligne.",
      en: "A complete platform for discovering and exploring Malagasy song lyrics, giving access to more than 15,000 songs by 2,300 artists with smart search, personalization and offline access.",
    },
    gallery: [
      "/images/tononkira/tononkira_1.webp",
      "/images/tononkira/tononkira_2.webp",
      "/images/tononkira/tononkira_3.webp",
      "/images/tononkira/tononkira_4.webp",
    ],
    tech: ["Flutter", "Dart", "Next.js", "Search Engine", "Offline-first"],
    highlights: [
      {
        fr: "Application mobile Android avec Flutter offrant un accès hors ligne complet aux paroles.",
        en: "Android mobile app built with Flutter, with full offline access to lyrics.",
      },
      {
        fr: "Moteur de recherche performant permettant de trouver des chansons par paroles, artiste ou titre.",
        en: "Fast search engine to find songs by lyrics, artist or title.",
      },
      {
        fr: "Système de favoris et de playlists personnalisées pour une expérience optimale.",
        en: "Favorites and custom playlists for the best possible experience.",
      },
      {
        fr: "Optimisation des performances pour une application légère et rapide sur tous les appareils.",
        en: "Performance tuning for a light, fast app on every device.",
      },
      {
        fr: "Base de données de plus de 15 000 chansons et 2 300 artistes malgaches.",
        en: "A database of more than 15,000 songs and 2,300 Malagasy artists.",
      },
    ],
    stats: [
      {
        k: { fr: "15 000+", en: "15,000+" },
        v: { fr: "Chansons", en: "Songs" },
      },
      { k: { fr: "2 300", en: "2,300" }, v: { fr: "Artistes", en: "Artists" } },
      { k: "100%", v: { fr: "Hors-ligne", en: "Offline" } },
    ],
  },
  {
    slug: "chantastik",
    name: "Chantastik",
    tag: "Remotion · Web Audio API",
    img: "/images/chantastik/chantastik_1.webp",
    thumb: "/images/chantastik/chantastik_2.webp",
    url: "https://chantastik.titosy.dev/",
    github: "https://github.com/titoo-dev/chantastik",
    year: "2024",
    type: { fr: "Application Web", en: "Web App" },
    desc: {
      fr: "Crée des vidéos lyriques animées depuis un fichier audio, avec synchronisation précise et export de fichiers LRC.",
      en: "Creates animated lyric videos from an audio file, with precise syncing and LRC file export.",
    },
    overview: {
      fr: "Une application qui permet de créer de superbes vidéos de paroles à partir de fichiers audio, avec de magnifiques animations et des effets visuels personnalisables.",
      en: "An app for creating stunning lyric videos from audio files, with beautiful animations and customizable visual effects.",
    },
    gallery: [
      "/images/chantastik/chantastik_1.webp",
      "/images/chantastik/chantastik_2.webp",
      "/images/chantastik/chantastik_3.webp",
      "/images/chantastik/chantastik_4.webp",
    ],
    tech: ["Remotion", "Web Audio API", "React", "TypeScript", "LRC"],
    highlights: [
      {
        fr: "Rendu vidéo des paroles animées propulsé par Remotion.",
        en: "Animated lyric video rendering powered by Remotion.",
      },
      {
        fr: "Web Audio API pour synchroniser précisément l'audio avec les animations.",
        en: "Web Audio API to precisely sync the audio with the animations.",
      },
      {
        fr: "Système d'annotation des lyrics avec interface intuitive pour le timing.",
        en: "Lyric annotation system with an intuitive timing interface.",
      },
      {
        fr: "Génération automatique de fichiers LRC pour la compatibilité avec d'autres lecteurs.",
        en: "Automatic LRC file generation for compatibility with other players.",
      },
    ],
    stats: [
      { k: "Frame", v: { fr: "Sync parfaite", en: "Perfect sync" } },
      { k: "LRC", v: "Export" },
      { k: "OSS", v: "Open source" },
    ],
  },
  {
    slug: "magape",
    name: "MAGAPE",
    tag: "Next.js · TypeScript · Tailwind",
    img: "/images/magape/magape_1.webp",
    thumb: "/images/magape/magape_2.webp",
    url: "https://megape.vercel.app/",
    github: null,
    year: "2024",
    type: { fr: "Plateforme communautaire", en: "Community platform" },
    desc: {
      fr: "Plateforme communautaire chrétienne francophone avec podcasts, enseignements bibliques & boutique en ligne.",
      en: "French-speaking Christian community platform with podcasts, Bible teachings & an online store.",
    },
    overview: {
      fr: "Plateforme dédiée à rassembler la communauté chrétienne francophone à travers des ressources enrichissantes, des contenus audiovisuels et des produits inspirants, créant des ponts d'unité entre les chrétiens.",
      en: "A platform that brings the French-speaking Christian community together through enriching resources, audiovisual content and inspiring products, building bridges of unity between Christians.",
    },
    gallery: [
      "/images/magape/magape_1.webp",
      "/images/magape/magape_2.webp",
      "/images/magape/magape_3.webp",
      "/images/magape/magape_4.webp",
    ],
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "CMS", "E-commerce"],
    highlights: [
      {
        fr: "Plateforme complète avec Next.js et TypeScript pour la francophonie chrétienne.",
        en: "Complete platform built with Next.js and TypeScript for French-speaking Christians.",
      },
      {
        fr: "Système de gestion de contenu pour podcasts, émissions et enseignements bibliques.",
        en: "Content management system for podcasts, shows and Bible teachings.",
      },
      {
        fr: "Boutique en ligne intégrée pour les produits MAGAPE (maillots, ebooks, cahiers).",
        en: "Built-in online store for MAGAPE products (jerseys, ebooks, notebooks).",
      },
      {
        fr: "Interface moderne et responsive avec Tailwind CSS.",
        en: "Modern, responsive interface with Tailwind CSS.",
      },
      {
        fr: "Cahier Magape Kids, un outil éducatif centré sur la Bible pour les enfants.",
        en: "Magape Kids notebook, a Bible-centered learning tool for children.",
      },
    ],
    stats: [
      { k: "CMS", v: { fr: "Contenus", en: "Content" } },
      { k: "Shop", v: { fr: "Boutique", en: "Store" } },
      { k: "FR", v: { fr: "Francophone", en: "French-speaking" } },
    ],
  },
  {
    slug: "okani-survey",
    name: "Okani Survey",
    tag: "Next.js · Mobile · Gov",
    img: "/images/okani-survey/okani_1.webp",
    thumb: "/images/okani-survey/okani_2.webp",
    url: "https://okani-survey.vercel.app/",
    github: null,
    year: "2025",
    type: { fr: "Plateforme gouvernementale", en: "Government platform" },
    desc: {
      fr: "Plateforme de sondage gouvernementale (Gabon) évaluant le service public foncier. Web + app cross-platform.",
      en: "Government survey platform (Gabon) assessing the public land service. Web + cross-platform app.",
    },
    overview: {
      fr: "Plateforme de sondage gouvernementale officielle évaluant la satisfaction des usagers du service public foncier au Gabon, mandatée par la DGCBF dans le cadre de la modernisation de l'administration publique.",
      en: "Official government survey platform measuring user satisfaction with the public land service in Gabon, commissioned by the DGCBF as part of the modernization of public administration.",
    },
    gallery: [
      "/images/okani-survey/okani_1.webp",
      "/images/okani-survey/okani_2.webp",
      "/images/okani-survey/okani_3.webp",
    ],
    tech: ["Next.js", "TypeScript", "Cross-platform", "Tailwind CSS", "Mobile"],
    highlights: [
      {
        fr: "Plateforme web interactive avec Next.js pour recueillir les retours des usagers.",
        en: "Interactive web platform built with Next.js to collect user feedback.",
      },
      {
        fr: "Application mobile cross-platform disponible sur App Store et Google Play.",
        en: "Cross-platform mobile app available on the App Store and Google Play.",
      },
      {
        fr: "Processus de sondage simplifié en 6 étapes couvrant le parcours foncier (ANUTTC).",
        en: "Streamlined 6-step survey covering the land registration journey (ANUTTC).",
      },
      {
        fr: "Système de collecte de données anonyme et sécurisé garantissant la confidentialité.",
        en: "Anonymous, secure data collection that guarantees confidentiality.",
      },
      {
        fr: "Déploiement ciblé : Libreville, Lambaréné et Mouila.",
        en: "Targeted rollout: Libreville, Lambaréné and Mouila.",
      },
    ],
    stats: [
      { k: "6", v: { fr: "Étapes", en: "Steps" } },
      { k: "5-10 min", v: { fr: "Durée", en: "Duration" } },
      { k: "3", v: { fr: "Villes", en: "Cities" } },
    ],
  },
];

const services: Localizable<Service>[] = [
  {
    label: "Web",
    title: { fr: "Développement Web", en: "Web Development" },
    body: {
      fr: "Applications web modernes et performantes avec React, Next.js et TypeScript.",
      en: "Modern, high-performance web apps with React, Next.js and TypeScript.",
    },
    features: [
      "React / Next.js",
      { fr: "Sites responsives", en: "Responsive websites" },
      "Progressive Web Apps",
      { fr: "Intégration API", en: "API integration" },
    ],
  },
  {
    label: "Mobile",
    title: { fr: "Applications Mobile", en: "Mobile Apps" },
    body: {
      fr: "Applications cross-platform avec Flutter. Une expérience fluide sur iOS et Android.",
      en: "Cross-platform apps with Flutter. A smooth experience on iOS and Android.",
    },
    features: [
      { fr: "Apps Flutter", en: "Flutter apps" },
      { fr: "UI/UX mobile", en: "Mobile UI/UX" },
      { fr: "Intégration Firebase", en: "Firebase integration" },
      "App Store & Play Store",
    ],
  },
  {
    label: "Design",
    title: { fr: "Design UI/UX", en: "UI/UX Design" },
    body: {
      fr: "Interfaces élégantes et accessibles avec Figma. Des designs modernes qui captivent.",
      en: "Elegant, accessible interfaces with Figma. Modern designs that captivate.",
    },
    features: [
      { fr: "Prototypage Figma", en: "Figma prototyping" },
      "Design System",
      { fr: "Interface responsive", en: "Responsive interfaces" },
      { fr: "Accessibilité", en: "Accessibility" },
    ],
  },
  {
    label: "Consulting",
    title: { fr: "Consulting & Formation", en: "Consulting & Training" },
    body: {
      fr: "Accompagnement technique et formation de vos équipes sur les technologies modernes.",
      en: "Technical guidance and training for your teams on modern technologies.",
    },
    features: [
      { fr: "Audit technique", en: "Technical audit" },
      { fr: "Formation React/Flutter", en: "React/Flutter training" },
      "Code review",
      { fr: "Bonnes pratiques", en: "Best practices" },
    ],
  },
];

const stack: Localizable<StackGroup>[] = [
  {
    label: "Frontend",
    items: ["Next.js", "React", "TypeScript", "Tailwind CSS", "ExtJS"],
  },
  {
    label: "Backend",
    items: [
      "Node.js",
      "Nest.js",
      "Express",
      "GraphQL",
      "PostgreSQL",
      "TypeORM",
    ],
  },
  {
    label: "Mobile",
    items: ["Flutter", "Dart", "Kotlin", "Firebase"],
  },
  {
    label: "DevOps",
    items: [
      "Terraform",
      "Kubernetes",
      "ArgoCD",
      "Prometheus",
      "Grafana",
      "Docker",
    ],
  },
  {
    label: { fr: "IA & Outils", en: "AI & Tools" },
    items: [
      "Convex AI",
      "Mastra AI",
      "Inngest",
      "Claude Code",
      "LangGraph",
      "Langchain",
      "Figma",
    ],
  },
];

function isPair(value: object): value is T<unknown> {
  const keys = Object.keys(value);
  return keys.length === 2 && "fr" in value && "en" in value;
}

function resolve<V>(value: V, locale: Locale): Resolved<V> {
  if (Array.isArray(value)) {
    return value.map((v) => resolve(v, locale)) as Resolved<V>;
  }
  if (value && typeof value === "object") {
    if (isPair(value)) return value[locale] as Resolved<V>;
    return Object.fromEntries(
      Object.entries(value).map(([k, v]) => [k, resolve(v, locale)]),
    ) as Resolved<V>;
  }
  return value as Resolved<V>;
}

export type Content = {
  PROFILE: Resolved<typeof PROFILE>;
  careers: Career[];
  projects: Project[];
  services: Service[];
  stack: StackGroup[];
};

const cache = new Map<Locale, Content>();

/** Every piece of portfolio data, in one language. */
export function getContent(locale: Locale): Content {
  let content = cache.get(locale);
  if (!content) {
    content = resolve(
      { PROFILE, careers, projects, services, stack },
      locale,
    ) as Content;
    cache.set(locale, content);
  }
  return content;
}

/** Project slugs are shared by every locale. */
export const projectSlugs = projects.map((p) => p.slug);

export function getProject(locale: Locale, slug: string): Project | undefined {
  return getContent(locale).projects.find((p) => p.slug === slug);
}
